### PR TITLE
Update 2022

### PR DESCRIPTION
**Pull request by lgelauff**
Based on #41, and the feedback there I made some additional changes after looking at the patches by @bodhisattwawiki last year.

### CODE REVIEW

**Comment by lokal-profil** [comment]
@mahmoud is Monumental aware of which countries are running WLM (since one of the updated strings is an error message about that) and if so is that info hosted somewhere which also needs an update?

**Comment by lgelauff** [comment]
@lokal-profil country codes are seemingly being tracked in `src/components/main/monument/monument.html` in:

`ng-if="$ctrl.country && ['pl', 'ie', 'gb', 'se'].indexOf($ctrl.country.code) === -1"`

I don't have sufficient understanding of the code to mess with that though - e.g. what wikidata infrastructure would have to be there to add a country, and how to tie that all together.

**Comment by lokal-profil** [comment]
@lgelauff Thanks. So the "not in wlm this year" message just translates to "not fully supported by Monumental". In that case it should be fine to leave that bit un-updated.

**Comment by lokal-profil** [comment]
@mahmoud do you see anything missing in the patch or is it good to go?

**Review by mahmoud — APPROVED** [review]
LGTM, thanks!

**Comment by mahmoud** [comment]
Will aim to get this deployed today and will circle back here / on the thread.

**Comment by mahmoud** [comment]
:wave: Alright, deployed and clicktested, seems to be working for me. Feel free to test: https://maps.wikilovesmonuments.org/

**Comment by lokal-profil** [comment]
Many thanks for the quick response!

**Pull request merged**
