### PR TITLE
Update strings to 2022

### PR DESCRIPTION
**Pull request by misaochan**

### CODE REVIEW

**Review by mahmoud — COMMENTED** [review]
Hey there! Thanks for this. Is this change intended just for display and links? Because there are a few other functional places which need category updates to work for 2022. See here: https://github.com/hatnote/monumental-wlm/blob/c43cacc1fa3281c5f7400fa3ed702f04e4144635/src/components/main/monument/monument.js#L145

**Comment by misaochan** [comment]
Ah sorry, I'm not very familiar with this repo and only made the changes to try and help out the national organizers. Unfortunately I don't have the time to look further into which other places need modifications.

**Comment by Smirkybec** [comment]
@mahmoud is it possible to get it updated for 2022 - otherwise we don't have a platform to run WLM in Ireland!

**Comment by Smirkybec** [comment]
> @mahmoud is it possible to get it updated for 2022 - otherwise we don't have a platform to run WLM in Ireland!

And this pull request was based on your previous one from last year: https://github.com/hatnote/monumental-wlm/commit/c43cacc1fa3281c5f7400fa3ed702f04e4144635

**Pull request merged**
